NAME = main
SRC  = PhoneBook.cpp Contact.cpp main.cpp
OBJ = $(SRC:.cpp=.o)
CC =  g++
FLAGS = -Wall -Wextra -Werror -std=c++98

all:$(NAME)


%.o:%.cpp
			$(CC) $(FLAGS) -c $< -o $@

$(NAME) : $(OBJ)
				$(CC) $(OBJ) -o $(NAME)
				@echo "Compiling done."

clean :
		@rm -rf $(OBJ)

fclean : clean
		@rm -f $(NAME)

re : fclean all
